.class public final Lsh/p$a;
.super Ljava/lang/Object;
.source "SourceFile"


# annotations
.annotation system Ldalvik/annotation/EnclosingClass;
    value = Lsh/p;
.end annotation

.annotation system Ldalvik/annotation/InnerClass;
    accessFlags = 0x19
    name = "a"
.end annotation


# instance fields
.field private a:Ljava/lang/String;

.field private b:Ljava/lang/String;

.field private c:Z

.field private d:Lsh/d;

.field private e:Lwg/i;

.field private f:Ljava/lang/String;

.field private g:Ljava/lang/String;

.field private h:Ljava/lang/Boolean;


# direct methods
.method public constructor <init>()V
    .locals 1

    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    sget-object v0, Lsh/d;->f:Lsh/d;

    iput-object v0, p0, Lsh/p$a;->d:Lsh/d;

    return-void
.end method


# virtual methods
.method public a()Lsh/p;
    .locals 11

    iget-object v0, p0, Lsh/p$a;->b:Ljava/lang/String;

    if-eqz v0, :cond_5

    iget-object v0, p0, Lsh/p$a;->d:Lsh/d;

    if-eqz v0, :cond_4

    iget-object v0, p0, Lsh/p$a;->g:Ljava/lang/String;

    if-eqz v0, :cond_3

    iget-object v1, p0, Lsh/p$a;->h:Ljava/lang/Boolean;

    if-eqz v1, :cond_2

    iget-object v1, p0, Lsh/p$a;->a:Ljava/lang/String;

    if-nez v1, :cond_1

    iget-object v1, p0, Lsh/p$a;->e:Lwg/i;

    if-eqz v1, :cond_0

    iget-object v1, v1, Lwg/i;->q:Ljava/lang/String;

    new-instance v2, Ljava/lang/StringBuilder;

    invoke-direct {v2}, Ljava/lang/StringBuilder;-><init>()V

    const-string v3, "."

    invoke-virtual {v2, v3}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    invoke-virtual {v2, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    invoke-virtual {v2}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object v1

    goto :goto_0

    :cond_0
    const-string v1, ""

    :goto_0
    new-instance v2, Ljava/lang/StringBuilder;

    invoke-direct {v2}, Ljava/lang/StringBuilder;-><init>()V

    invoke-virtual {v2, v0}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    invoke-virtual {v2, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    invoke-virtual {v2}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object v0

    iput-object v0, p0, Lsh/p$a;->a:Ljava/lang/String;

    :cond_1
    new-instance v0, Lsh/p;

    iget-object v2, p0, Lsh/p$a;->a:Ljava/lang/String;

    iget-object v3, p0, Lsh/p$a;->b:Ljava/lang/String;

    iget-boolean v4, p0, Lsh/p$a;->c:Z

    iget-object v5, p0, Lsh/p$a;->e:Lwg/i;

    iget-object v6, p0, Lsh/p$a;->d:Lsh/d;

    iget-object v7, p0, Lsh/p$a;->g:Ljava/lang/String;

    iget-object v1, p0, Lsh/p$a;->h:Ljava/lang/Boolean;

    invoke-virtual {v1}, Ljava/lang/Boolean;->booleanValue()Z

    move-result v8

    iget-object v9, p0, Lsh/p$a;->f:Ljava/lang/String;

    const/4 v10, 0x0

    move-object v1, v0

    invoke-direct/range {v1 .. v10}, Lsh/p;-><init>(Ljava/lang/String;Ljava/lang/String;ZLwg/i;Lsh/d;Ljava/lang/String;ZLjava/lang/String;Lsh/q;)V

    return-object v0

    :cond_2
    new-instance v0, Ljava/lang/IllegalStateException;

    const-string v1, "The subtitles stream has been not set as an autogenerated subtitles stream or not. Please specify this information with setIsAutoGenerated."

    invoke-direct {v0, v1}, Ljava/lang/IllegalStateException;-><init>(Ljava/lang/String;)V

    throw v0

    :cond_3
    new-instance v0, Ljava/lang/IllegalStateException;

    const-string v1, "The language code of the subtitles stream has been not set or is null. Make sure you specified an non null language code with setLanguageCode."

    invoke-direct {v0, v1}, Ljava/lang/IllegalStateException;-><init>(Ljava/lang/String;)V

    throw v0

    :cond_4
    new-instance v0, Ljava/lang/IllegalStateException;

    const-string v1, "The delivery method of the subtitles stream has been set as null, which is not allowed. Pass a valid one instead withsetDeliveryMethod."

    invoke-direct {v0, v1}, Ljava/lang/IllegalStateException;-><init>(Ljava/lang/String;)V

    throw v0

    :cond_5
    new-instance v0, Ljava/lang/IllegalStateException;

    const-string v1, "No valid content was specified. Please specify a valid one with setContent."

    invoke-direct {v0, v1}, Ljava/lang/IllegalStateException;-><init>(Ljava/lang/String;)V

    throw v0
.end method

.method public b(Z)Lsh/p$a;
    .locals 0

    invoke-static {p1}, Ljava/lang/Boolean;->valueOf(Z)Ljava/lang/Boolean;

    move-result-object p1

    iput-object p1, p0, Lsh/p$a;->h:Ljava/lang/Boolean;

    return-object p0
.end method

.method public c(Ljava/lang/String;Z)Lsh/p$a;
    .locals 0

    iput-object p1, p0, Lsh/p$a;->b:Ljava/lang/String;

    iput-boolean p2, p0, Lsh/p$a;->c:Z

    return-object p0
.end method

.method public d(Ljava/lang/String;)Lsh/p$a;
    .locals 0

    iput-object p1, p0, Lsh/p$a;->g:Ljava/lang/String;

    return-object p0
.end method

.method public e(Lwg/i;)Lsh/p$a;
    .locals 0

    iput-object p1, p0, Lsh/p$a;->e:Lwg/i;

    return-object p0
.end method
